# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
