# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160121_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
