# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58dc39c94525448ee2c43a28764ebf49ef74f3196a4260c31ce7d991ba5d594ec2ab6d49c4441e6fc443289646502918aea9129a0bd10fa7cfa08974e7a314f4

test:
  secret_key_base: e2aa12f291ae9799c09131b5a25051533fe4caef92b6b5a2effea9818b365211de394526f2004c2ada199b12af321ce4e76d823dba7daaf1776ca1d2ed49eb6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
